## //-- BASIC INFO --// ##
esphome:
  name: "fancontrol-werkkamer"
  friendly_name: Fancontrol-werkkamer

esp8266:
  board: d1_mini

web_server:
  port: 80

time:
  - platform: homeassistant
    id: homeassistant_time

#logging
logger:
  level: info

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-3Aeac6"
    password: "<<redacted>>"

captive_portal:


## //-- SENSOR AND ADDON CONFIG --// ##
## 2x Dalles op Pin 14 (D5)
## 1x Template Delta T sensor (Tin - Tout)
## Pulse counter op Pin 0 (D3)
## PWM Output fan op Pin 4 (D2)
## Relay voor 12v op Pin 5 (D1)


# Dalles, 18BS20 temperature sensors
#dallas:
#  - pin: 14
#    update_interval: 20s


sensor:
#  - platform: dallas
#    address: 0x246b7e701f64ff28
#    name: "Tin"
#    id: tin
#    accuracy_decimals: 1
#
#  - platform: dallas
#    address: 0xf46fde7f1f64ff28
#    name: "Tout"
#    id: tout
#    accuracy_decimals: 1
#
#  # Delta T
#  - platform: template
#    name: "Td"
#    id: delta_t
#    update_interval: 20s
#    unit_of_measurement: "°C"
#    lambda: |-
#      return (id(tin).state - id(tout).state);
#    accuracy_decimals: 1


  #pulse counter for RPM readout
  - platform: pulse_counter
    pin: GPIO4
    name: "Fan RPM"
    id: fanrpm
    filters:
       - multiply: 0.5
#      - calibrate_linear:
#          method: least_squares
#          datapoints:
#            # Map 0.0 (from sensor) to 1.0 (true value)
#            - 0.0 -> 0.0
#            - 1750 -> 800
    count_mode:
      rising_edge: INCREMENT
      falling_edge: DISABLE
    update_interval: 10s
    accuracy_decimals: 0
    unit_of_measurement: 'RPM'

  #Wifi strength
  - platform: wifi_signal
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

# PWM fan GPIO5 == D1
output:
  - platform: esp8266_pwm
    id: fan_output
    pin: GPIO5
    frequency: 1000hz

#output:
#  - platform: esp8266_pwm
#    id: fan_speed
#    pin: D1
#
#    frequency: "25000 Hz"

#    min_power: 13%
#    max_power: 100%

#fan:
#  - platform: speed
#    output: fan_speed
#    name: fan speed
#    id: fan_toggle

# Fan slider control
fan:
  - platform: speed
    name: "fanspeed"
    output: fan_output
#    on_turn_on:
#      - logger.log: "Fan Turned On!"
#      - switch.turn_on: relay
#    on_turn_off:
#      - logger.log: "Fan Turned Off!"
#      - switch.turn_off: relay

# Relay 12v
switch:
#  - platform: gpio
#    name: "Relay 12v"
#    id: relay
#    pin: 5
#    internal: True

  # Reboot button
  - platform: restart
    name: "Reboot device"
    entity_category: "diagnostic"

# Diagnostic Wifi info
text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
      entity_category: "diagnostic"
    ssid:
      name: ESP Connected SSID
      entity_category: "diagnostic"