esphome:
  name: eastron-goodwe
  platform: ESP8266
  board: d1_mini

# Enable/Disable logging
logger:
  #level: VERBOSE
  #baud_rate: 0

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESP-EastronGoodwe"
    password: "configesp"

captive_portal:

# Do request do Domoticz
http_request:
  useragent: esphome/device
  timeout: 10s

uart:
  id: mod_bus
  tx_pin: D7
  rx_pin: D6
  baud_rate: 9600
  stop_bits: 1
  
modbus:
  flow_control_pin: D5
  id: modbus1
  send_wait_time: 1000ms

modbus_controller:
  - id: goodwe
    ## the Modbus device addr (defaults to 247 (0xF7) for goodwe inverters)
    address: 0xF7
    modbus_id: modbus1
    setup_priority: -10
    #command_throttle: 250ms
    update_interval: 15s

sensor:
  - platform: modbus_controller
    modbus_controller_id: goodwe
    id: pv_temperature
    name: "Temperature"
    address: 0x030F
    unit_of_measurement: "C"
    register_type: holding
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: goodwe
    id: pv_power
    name: "Feeding Power"
    address: 0x0233
    unit_of_measurement: "W"
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 0
    on_value:
    - http_request.get:
        url: !lambda |-
          char buf1[64];
          char buf2[64];
          sprintf(buf1, "%0.0f", id(pv_power).state);
          sprintf(buf2, "%0.3f", id(pv_total_energy).state);
          return ((std::string) "http://192.168.38.208:8080/json.htm?type=command&param=udevice&idx=4265&nvalue=0&svalue=" + buf1 + ";" + buf2).c_str();

  - platform: modbus_controller
    modbus_controller_id: goodwe
    id: pv_total_energy
    name: "Total Energy"
    address: 0x0313
    unit_of_measurement: "kWh"
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 100

  - platform: modbus_controller
    modbus_controller_id: goodwe
    id: pv_day_energy
    name: "Day Energy"
    address: 0x0236
    unit_of_measurement: "kWh"
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: goodwe
    id: pv_e_day
    name: "E-Day"
    address: 0x0320
    unit_of_measurement: "kWh"
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: goodwe
    id: pv_p_ac
    name: "Pac"
    address: 0x0353
    unit_of_measurement: "W"
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: goodwe
    id: pv_total_hours
    name: "Total Hours"
    address: 0x0314
    unit_of_measurement: "H"
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 0

  - platform: sdm_meter
    phase_a:
      current:
        name: "SDM220M Current"
      voltage:
        name: "SDM220M Voltage"
      active_power:
        name: "SDM220M Power"
      power_factor:
        name: "SDM220M Power Factor"
      apparent_power:
        name: "SDM220M Apparent Power"
      reactive_power:
        name: "SDM220M Reactive Power"
      phase_angle:
        name: "SDM220M Phase Angle"
    frequency:
      name: "SDM220M Frequency"
    import_active_energy:
      name: "SDM220M Import Active Energy"
    export_active_energy:
      name: "SDM220M Export Active Energy"
    import_reactive_energy:
      name: "SDM220M Import Reactive Energy"
    export_reactive_energy:
      name: "SDM220M Export Reactive Energy"
    update_interval: 10s
    address: 1
