esphome:
  name: relay-doorbell
  platform: ESP8266
  board: d1_mini

switch:
  - platform: gpio
    pin:
      number: D2
      inverted: false
    name: "Relay1"
#  - platform: gpio
#    pin:
#      number: D2
#      inverted: true
#    name: "Relay2"
#  - platform: gpio
#    pin:
#      number: D5
#      inverted: true
#    name: "Relay3"
#  - platform: gpio
#    pin:
#      number: D6
#      inverted: true
#    name: "Relay4"

logger:
  level: DEBUG

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESPHOME-relayDoorbell"
    password: "configesp"

captive_portal:
